[package]
name = "sparse-interp"
version = "0.1.0"
authors = ["Daniel S. Roche <dsroche@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
